[tool.black]
target-version = ['py311']
include = '\.pyi?$'
exclude = "migrations"

[tool.ruff]
target-version = "py38"
exclude = ["migrations"]
select = ["ALL"]
ignore = [
  "ANN",      # Missing Annotations
  "ARG",      # Unused function/method argument
  "D",        # Missing or badly formatted docstrings
  "E501",     # Line too long (>88)
  "EM",       # Exception must not use <string format>
  "FBT",      # Flake Boolean Trap (don't use arg=True in functions)
  "PLR2004",  # Magic value used in comparison, consider replacing <int> with a constant variable
  "PT009",    # Use a regular `assert` instead of unittest-style `assertEqual`
  "RUF005",   # Consider `(list, *list) instead of concatenation
  "S101",     # Use of `assert` detected
  "SLF001",   # Private member accessed"
  "TCH",      # Type-checking
  "TID252",   # Relative imports from parent modules are banned (from ..foo import bar)"
  "TRY003",   # Avoid specifying long messages outside the exception class
]

[tool.pytest.ini_options]
python_files = [
  "tests.py",
  "test_*.py",
  "*_tests.py",
]
addopts = """
    --ds=django_markup.tests.settings
    --cov=./django_markup
    --cov-append
    --cov-branch
    --nomigrations
    --reuse-db
"""
filterwarnings = ["ignore::RuntimeWarning"]


